name: EventTP
main: com.github.PhoenixReborn.EventTP.EventTP
version: 1.01
author: Polaris120990
commands:
  openevent:
    description: This command opens an event that players can join.
    usage: /<command> [message]
    permission: <plugin name>.open
  closeevent:
    description: This command closes an event if there is one currently open.
    usage: /<command>
    permission: <plugin name>.close
  joinevent:
    description: This command teleports a player to the location of an event.
    usage: /<command>
    permission: <plugin name>.join
permissions:
  eventtp.open:
    description: Allows use of the openevent command.
  eventtp.close:
    description: Allows use of the closeevent command.
  eventtp.join:
    description: Allows use of the joinevent command.